### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by lubien** [DestructHub/programming-challenge-2016#3]
Since this repo mostly like to have the structure to work with SBC's marathon, maybe a more descriptive name should be better.

> A Maratona de Programação é um evento da Sociedade Brasileira de Computação que existe desde o ano de 1996. A Maratona nasceu das competições regionais classificatórias para as finais mundiais do concurso de programação da ACM, o ACM International Collegiate Programming Contest, e é parte da regional sulamericana do concurso. Neste ano ocorre a 21a. edição da Maratona.

**Comment by ryukinix** [comment]
@lubien Great idea. I approve this.

**Comment by lubien** [comment]
Maybe `sbc-programming-marathon`.

**Comment by lubien** [comment]
Seems like SBC calls himself as Brazilian Computer Society (BCS) in english.
http://sbc.org.br/publicacoes-2/374-jbcs

**Comment by ryukinix** [comment]
@lubien how about `jbcs-challenges`?

**Comment by lubien** [comment]
@ryukinix the "j" at the the init is for the "Journal". 
`bcs-challenges` seems great

**Comment by ryukinix** [comment]
@lubien Oh, I was wondering about that. Great. I approve.

**Comment by lubien** [comment]
But wouldn't be better point in the name that this is a marathon?
`bcs-marathon`

**Comment by ryukinix** [comment]
`contest` is better, actually.

**Comment by ryukinix** [comment]
In English is very common the usage of word `contest` for challenges, marathons and other type of competitions.

**Comment by lubien** [comment]
@ryukinix `bcs-contest` then?

**Comment by ryukinix** [comment]
@lubien Yes.

**Comment by ryukinix** [comment]
@ryukinix I renamed the repository right know. Check it.

**Comment by lubien** [comment]
Awesome
